services:
  web:
    build:
      context: .
      target: build
    ports:
      # web socket server that remix uses for development
      - "8002:8002"
        # prisma studio, which can be run with `docker exec` when needed
      - "5555:5555"
        # node debugger
      - "9229:9229"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      NODE_ENV: development

volumes:
  node_modules:
