services:
  web:
    image: ${IMAGE}
    build: .
    ports:
      # http server
      - "8000:8000"
    links:
      - db
    environment:
      DATABASE_URL: postgresql://app:app@db/app
      ADMIN_PASSWORD: pass
      SESSION_SECRET: anything
      EMAIL_PASSWORD: ${KATE_WEBSITE_EMAIL_PASSWORD:-nopass}
  db:
    image: postgres:14
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    ports:
      # we're going to expose the db to the host machine for integration
      # testing, but not use the traditional postgres port to avoid collisions
      # with existing postgres installations
      - 4050:5432

volumes:
  pg_data:
