# Generated by Django 3.2.9 on 2021-11-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinquiry',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
