name: CI/CD

on:
  push:
    branch: ['main']
  pull_request:

jobs:

  ci:
    name: continuous integration checks
    runs-on: ubuntu-latest
    environment: Kubernetes
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: CI Cache
        id: cache
        uses: actions/cache@v3
        with:
          path: cache
          key: cache
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: make check
        run: make check

  push_container:
    name: build and push Docker container
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    environment: Kubernetes
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/checkout@v2
      - name: CI Cache
        id: cache
        uses: actions/cache@v3
        with:
          path: cache
          key: cache
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          cache-from: type=local,src=cache/docker
          cache-to: type=local,src=cache/docker
      - name: login to docker hub
        uses: docker/login-action@v1
        with:
          username: jdevries3133
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: push container to Docker Hub
        run: make push

  deploy:
    name: deploy to Kubernetes with Terraform
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    needs: [ci, push_container]
    environment: Kubernetes
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: setup kubectl
        run: |
          mkdir ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config
      - name: perform deployment
        env:
          # credentials are used for terraform state bucket
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: make deploy
